name: construction_marketplace
description: A marketplace app for construction materials.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^5.6.7
  flutter_typeahead: ^4.8.0
  file_picker: ^10.1.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  jwt_decoder: ^2.0.1
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  image_picker: ^1.0.4
  path: ^1.8.3
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  universal_html: ^2.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/lang/